export const INDEX_ROUTE = '/'
export const SIGN_IN_ROUTE = '/auth/signin'
export const SIGN_UP_ROUTE = '/auth/signup'
export const PROFILE_ROUTE = 'profile'
export const WORKOUTS_ROUTE = '/workouts'
